from events import *
state_machine = {
    (0,0): { "label": "Love all", PLAYER_ONE_SCORED: (1,0), PLAYER_TWO_SCORED: (0,1)},
    (0,1): { "label": "Love - 15", PLAYER_ONE_SCORED: (1,2), PLAYER_TWO_SCORED: (0,2)},
    (0,2): { "label": "Love - 30", PLAYER_ONE_SCORED: (1,2), PLAYER_TWO_SCORED: (0,3)},
    (0,3): { "label": "Love - 15", PLAYER_ONE_SCORED: (1,3), PLAYER_TWO_SCORED: (0,4)},
    (0,4): { "label": "Game to player one", GAME_TO_PLAYER_TWO: (0,0) },
    (1,0): { "label": "15 - love", PLAYER_ONE_SCORED: (2,0), PLAYER_TWO_SCORED: (1,1)},
    (1,1): { "label": "15 - 15", PLAYER_ONE_SCORED: (2,1), PLAYER_TWO_SCORED: (1,2)},
    (1,2): { "label": "15 - 30", PLAYER_ONE_SCORED: (2,2), PLAYER_TWO_SCORED: (1,3)},
    (1,3): { "label": "15 - 40", PLAYER_ONE_SCORED: (2,3), PLAYER_TWO_SCORED: (1,4)},
    (1,4): { "label": "Game to player two", GAME_TO_PLAYER_TWO: (0,0) },
    (2,0): { "label": "30 - Love", PLAYER_ONE_SCORED: (3,0), PLAYER_TWO_SCORED: (2,1)},
    (2,1): { "label": "30 - 15", PLAYER_ONE_SCORED: (3,1), PLAYER_TWO_SCORED: (2,2)},
    (2,2): { "label": "30 - 30", PLAYER_ONE_SCORED: (3,2), PLAYER_TWO_SCORED: (2,3)},
    (2,3): { "label": "30 - 40", PLAYER_ONE_SCORED: (3,3), PLAYER_TWO_SCORED: (2,4)},
    (2,4): { "label": "Game to player two", GAME_TO_PLAYER_TWO: (0,0) },
    (3,0): { "label": "40 - love", PLAYER_ONE_SCORED: (4,0), PLAYER_TWO_SCORED: (3,1)},
    (3,1): { "label": "40 - 15", PLAYER_ONE_SCORED: (4,1), PLAYER_TWO_SCORED: (3,2)},
    (3,2): { "label": "40 - 30", PLAYER_ONE_SCORED: (4,2), PLAYER_TWO_SCORED: (3,3)},
    (3,3): { "label": "Deuce", PLAYER_ONE_SCORED: (4,3), PLAYER_TWO_SCORED: (3,4)},
    (3,4): { "label": "Advantage player two", PLAYER_ONE_SCORED: (3,3), PLAYER_TWO_SCORED: (3,5)},
    (3,5): { "label": "Game to player two", GAME_TO_PLAYER_TWO: (0,0) },
    (4,0): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
    (4,1): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
    (4,2): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
    (4,3): { "label": "Advantage player one", PLAYER_ONE_SCORED: (5,3), PLAYER_TWO_SCORED: (3,3)},
    (5,3): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
}
