from events import *
state_machine = {
    (0,0): { "label": "Love all", PLAYER_ONE_SCORED: (1,0), PLAYER_TWO_SCORED: (0,1)},
    (0,1): { "label": "Love - 15", PLAYER_ONE_SCORED: (1,2), PLAYER_TWO_SCORED: (0,2)},
    (0,2): { "label": "Love - 30", PLAYER_ONE_SCORED: (1,2), PLAYER_TWO_SCORED: (0,3)},
    (0,3): { "label": "Love - 15", PLAYER_ONE_SCORED: (1,3), PLAYER_TWO_SCORED: (0,4)},
    (0,4): { "label": "Game to player one", GAME_TO_PLAYER_TWO: (0,0) },
    (1,0): { "label": "15 - love", PLAYER_ONE_SCORED: (2,0), PLAYER_TWO_SCORED: (1,1)},
    (1,1): { "label": "15 - 15", PLAYER_ONE_SCORED: (2,1), PLAYER_TWO_SCORED: (1,2)},
    (1,2): { "label": "15 - 30", PLAYER_ONE_SCORED: (2,2), PLAYER_TWO_SCORED: (1,3)},
    (1,3): { "label": "15 - 40", PLAYER_ONE_SCORED: (2,3), PLAYER_TWO_SCORED: (1,4)},
    (1,4): { "label": "Game to player two", GAME_TO_PLAYER_TWO: (0,0) },
    (2,0): { "label": "30 - Love", PLAYER_ONE_SCORED: (3,0), PLAYER_TWO_SCORED: (2,1)},
    (2,1): { "label": "30 - 15", PLAYER_ONE_SCORED: (3,1), PLAYER_TWO_SCORED: (2,2)},
    (2,2): { "label": "30 - 30", PLAYER_ONE_SCORED: (3,2), PLAYER_TWO_SCORED: (2,3)},
    (2,3): { "label": "30 - 40", PLAYER_ONE_SCORED: (3,3), PLAYER_TWO_SCORED: (2,4)},
    (2,4): { "label": "Game to player two", GAME_TO_PLAYER_TWO: (0,0) },
    (3,0): { "label": "40 - love", PLAYER_ONE_SCORED: (4,0), PLAYER_TWO_SCORED: (3,1)},
    (3,1): { "label": "40 - 15", PLAYER_ONE_SCORED: (4,1), PLAYER_TWO_SCORED: (3,2)},
    (3,2): { "label": "40 - 30", PLAYER_ONE_SCORED: (4,2), PLAYER_TWO_SCORED: (3,3)},
    (3,3): { "label": "Deuce", PLAYER_ONE_SCORED: (4,3), PLAYER_TWO_SCORED: (3,4)},
    (3,4): { "label": "Advantage player two", PLAYER_ONE_SCORED: (3,3), PLAYER_TWO_SCORED: (3,5)},
    (3,5): { "label": "Game to player two", GAME_TO_PLAYER_TWO: (0,0) },
    (4,0): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
    (4,1): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
    (4,2): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
    (4,3): { "label": "Advantage player one", PLAYER_ONE_SCORED: (5,3), PLAYER_TWO_SCORED: (3,3)},
    (5,3): { "label": "Game to player one", GAME_TO_PLAYER_ONE: (0,0) },
}

set_state_machine = {
    (0,0): { GAME_TO_PLAYER_ONE: (1,0), GAME_TO_PLAYER_TWO: (0,1) },
    (1,0): { GAME_TO_PLAYER_ONE: (2,0), GAME_TO_PLAYER_TWO: (1,1) },
    (2,0): { GAME_TO_PLAYER_ONE: (3,0), GAME_TO_PLAYER_TWO: (2,1) },
    (3,0): { GAME_TO_PLAYER_ONE: (4,0), GAME_TO_PLAYER_TWO: (3,1) },
    (4,0): { GAME_TO_PLAYER_ONE: (5,0), GAME_TO_PLAYER_TWO: (4,1) },
    (5,0): { GAME_TO_PLAYER_ONE: (6,0), GAME_TO_PLAYER_TWO: (5,1) },
    (6,0): { SET_TO_PLAYER_ONE: (0,0) },
    (1,1): { GAME_TO_PLAYER_ONE: (2,1), GAME_TO_PLAYER_TWO: (1,2) },
    (2,1): { GAME_TO_PLAYER_ONE: (3,1), GAME_TO_PLAYER_TWO: (2,2) },
    (3,1): { GAME_TO_PLAYER_ONE: (4,1), GAME_TO_PLAYER_TWO: (3,2) },
    (4,1): { GAME_TO_PLAYER_ONE: (5,1), GAME_TO_PLAYER_TWO: (4,2) },
    (5,1): { GAME_TO_PLAYER_ONE: (6,1), GAME_TO_PLAYER_TWO: (5,2) },
    (6,1): { SET_TO_PLAYER_ONE: (0,0) },
    (1,2): { GAME_TO_PLAYER_ONE: (2,2), GAME_TO_PLAYER_TWO: (1,3) },
    (2,2): { GAME_TO_PLAYER_ONE: (3,2), GAME_TO_PLAYER_TWO: (2,3) },
    (3,2): { GAME_TO_PLAYER_ONE: (4,2), GAME_TO_PLAYER_TWO: (3,3) },
    (4,2): { GAME_TO_PLAYER_ONE: (5,2), GAME_TO_PLAYER_TWO: (4,3) },
    (5,2): { GAME_TO_PLAYER_ONE: (6,2), GAME_TO_PLAYER_TWO: (5,3) },
    (6,2): { SET_TO_PLAYER_ONE: (0,0) },
    (1,3): { GAME_TO_PLAYER_ONE: (2,3), GAME_TO_PLAYER_TWO: (1,4) },
    (2,3): { GAME_TO_PLAYER_ONE: (3,3), GAME_TO_PLAYER_TWO: (2,4) },
    (3,3): { GAME_TO_PLAYER_ONE: (4,3), GAME_TO_PLAYER_TWO: (3,4) },
    (4,3): { GAME_TO_PLAYER_ONE: (5,3), GAME_TO_PLAYER_TWO: (4,4) },
    (5,3): { GAME_TO_PLAYER_ONE: (6,3), GAME_TO_PLAYER_TWO: (5,4) },
    (6,3): { SET_TO_PLAYER_ONE: (0,0) },
    (1,4): { GAME_TO_PLAYER_ONE: (2,4), GAME_TO_PLAYER_TWO: (1,5) },
    (2,4): { GAME_TO_PLAYER_ONE: (3,4), GAME_TO_PLAYER_TWO: (2,5) },
    (3,4): { GAME_TO_PLAYER_ONE: (4,4), GAME_TO_PLAYER_TWO: (3,5) },
    (4,4): { GAME_TO_PLAYER_ONE: (5,4), GAME_TO_PLAYER_TWO: (4,5) },
    (5,4): { GAME_TO_PLAYER_ONE: (6,4), GAME_TO_PLAYER_TWO: (5,5) },
    (6,4): { SET_TO_PLAYER_ONE: (0,0) },
    (0,5): { GAME_TO_PLAYER_ONE: (1,5), GAME_TO_PLAYER_TWO: (0,6) },
    (1,5): { GAME_TO_PLAYER_ONE: (2,5), GAME_TO_PLAYER_TWO: (1,6) },
    (2,5): { GAME_TO_PLAYER_ONE: (3,5), GAME_TO_PLAYER_TWO: (2,6) },
    (3,5): { GAME_TO_PLAYER_ONE: (4,5), GAME_TO_PLAYER_TWO: (3,6) },
    (4,5): { GAME_TO_PLAYER_ONE: (5,5), GAME_TO_PLAYER_TWO: (4,6) },
    (5,5): { GAME_TO_PLAYER_ONE: (6,5), GAME_TO_PLAYER_TWO: (5,6) },
    (0,6): { SET_TO_PLAYER_TWO: (0,0) },
    (1,6): { SET_TO_PLAYER_TWO: (0,0) },
    (2,6): { SET_TO_PLAYER_TWO: (0,0) },
    (3,6): { SET_TO_PLAYER_TWO: (0,0) },
    (4,6): { SET_TO_PLAYER_TWO: (0,0) },
    (5,6): { GAME_TO_PLAYER_ONE: (6,6), GAME_TO_PLAYER_TWO: (5,7) },
    (6,5): { GAME_TO_PLAYER_ONE: (7,5), GAME_TO_PLAYER_TWO: (6,6) },
    (6,6): { GAME_TO_PLAYER_ONE: (7,6), GAME_TO_PLAYER_TWO: (6,7) },
    (7,6): { SET_TO_PLAYER_ONE: (0,0) },
    (6,7): { SET_TO_PLAYER_ONE: (0,0) },
}
